import jsPDF from 'jspdf';
import PptxGenJS from 'pptxgenjs';

// Generate clean filename from content
export const generateFilename = (content: string, type: string): string => {
  // Extract key words from content for filename
  const words = content
    .replace(/[^a-zA-Z0-9\s]/g, '')
    .split(/\s+/)
    .filter(word => word.length > 3)
    .slice(0, 4)
    .map(word => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase());
  
  const baseName = words.length > 0 ? words.join('_') : 'StudyBuddy_Content';
  return `${baseName}.${type}`;
};

// Download single image as PNG
export const downloadAsPNG = async (imageUrl: string, filename: string): Promise<void> => {
  try {
    const response = await fetch(imageUrl);
    const blob = await response.blob();
    const url = URL.createObjectURL(blob);
    
    const link = document.createElement('a');
    link.href = url;
    link.download = filename.endsWith('.png') ? filename : `${filename}.png`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  } catch (error) {
    console.error('Error downloading PNG:', error);
    throw error;
  }
};

// Download multiple images as PDF
export const downloadAsPDF = async (
  images: string[], 
  title: string,
  filename: string
): Promise<void> => {
  try {
    const pdf = new jsPDF({
      orientation: 'landscape',
      unit: 'mm',
      format: 'a4'
    });

    const pageWidth = pdf.internal.pageSize.getWidth();
    const pageHeight = pdf.internal.pageSize.getHeight();
    const margin = 15;

    // Add title page
    pdf.setFontSize(24);
    pdf.setTextColor(59, 130, 246); // Primary blue
    pdf.text(title, pageWidth / 2, 30, { align: 'center' });
    
    pdf.setFontSize(12);
    pdf.setTextColor(100, 100, 100);
    pdf.text('Generated by StudyBuddy AI', pageWidth / 2, 40, { align: 'center' });
    pdf.text(new Date().toLocaleDateString(), pageWidth / 2, 48, { align: 'center' });

    // Add each image on a new page
    for (let i = 0; i < images.length; i++) {
      pdf.addPage();
      
      // Add panel number header
      pdf.setFontSize(14);
      pdf.setTextColor(59, 130, 246);
      pdf.text(`Panel ${i + 1} of ${images.length}`, margin, 15);

      // Load and add image
      const img = await loadImage(images[i]);
      const imgAspect = img.width / img.height;
      
      const maxWidth = pageWidth - (margin * 2);
      const maxHeight = pageHeight - 30;
      
      let imgWidth = maxWidth;
      let imgHeight = imgWidth / imgAspect;
      
      if (imgHeight > maxHeight) {
        imgHeight = maxHeight;
        imgWidth = imgHeight * imgAspect;
      }

      const x = (pageWidth - imgWidth) / 2;
      const y = 25;

      pdf.addImage(img.src, 'PNG', x, y, imgWidth, imgHeight);
    }

    pdf.save(filename.endsWith('.pdf') ? filename : `${filename}.pdf`);
  } catch (error) {
    console.error('Error generating PDF:', error);
    throw error;
  }
};

// Download as PowerPoint presentation
export const downloadAsPPT = async (
  images: string[],
  title: string,
  filename: string
): Promise<void> => {
  try {
    const pptx = new PptxGenJS();
    pptx.title = title;
    pptx.author = 'StudyBuddy AI';

    // Title slide
    const titleSlide = pptx.addSlide();
    titleSlide.addText(title, {
      x: 0.5,
      y: 2,
      w: '90%',
      h: 1.5,
      fontSize: 36,
      bold: true,
      color: '3B82F6',
      align: 'center'
    });
    titleSlide.addText('Generated by StudyBuddy AI', {
      x: 0.5,
      y: 3.5,
      w: '90%',
      h: 0.5,
      fontSize: 18,
      color: '666666',
      align: 'center'
    });
    titleSlide.addText(new Date().toLocaleDateString(), {
      x: 0.5,
      y: 4,
      w: '90%',
      h: 0.5,
      fontSize: 14,
      color: '999999',
      align: 'center'
    });

    // Image slides
    for (let i = 0; i < images.length; i++) {
      const slide = pptx.addSlide();
      
      // Panel header
      slide.addText(`Panel ${i + 1}`, {
        x: 0.3,
        y: 0.2,
        w: 2,
        h: 0.4,
        fontSize: 14,
        bold: true,
        color: '3B82F6'
      });

      // Add image - convert to base64 if needed
      const base64 = await getBase64FromUrl(images[i]);
      slide.addImage({
        data: base64,
        x: 0.5,
        y: 0.7,
        w: 9,
        h: 4.5,
        sizing: { type: 'contain', w: 9, h: 4.5 }
      });
    }

    await pptx.writeFile({ fileName: filename.endsWith('.pptx') ? filename : `${filename}.pptx` });
  } catch (error) {
    console.error('Error generating PPT:', error);
    throw error;
  }
};

// Helper: Load image and return HTMLImageElement
const loadImage = (src: string): Promise<HTMLImageElement> => {
  return new Promise((resolve, reject) => {
    const img = new Image();
    img.crossOrigin = 'anonymous';
    img.onload = () => resolve(img);
    img.onerror = reject;
    img.src = src;
  });
};

// Helper: Convert image URL to base64
const getBase64FromUrl = async (url: string): Promise<string> => {
  try {
    const response = await fetch(url);
    const blob = await response.blob();
    return new Promise((resolve, reject) => {
      const reader = new FileReader();
      reader.onloadend = () => resolve(reader.result as string);
      reader.onerror = reject;
      reader.readAsDataURL(blob);
    });
  } catch (error) {
    console.error('Error converting to base64:', error);
    throw error;
  }
};
