// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/tools/list-agents.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.89.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-agents.ts
var list_agents_default = defineTool({
  name: "list_agents",
  title: "List my AI agents",
  description: "List the AI agents owned by the signed-in user.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).optional().describe("Max agents to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("agents").select("id, name, role, description, category, model, is_public, avatar_emoji, updated_at").order("updated_at", { ascending: false }).limit(limit ?? 20);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { agents: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-agent.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z2 } from "npm:zod@^3.25.76";
var create_agent_default = defineTool2({
  name: "create_agent",
  title: "Create an AI agent",
  description: "Create a new custom AI agent for the signed-in user.",
  inputSchema: {
    name: z2.string().trim().min(1).max(80).describe("Agent name."),
    role: z2.string().trim().max(200).optional().describe("Short role, e.g. 'Study tutor'."),
    system_prompt: z2.string().trim().max(8e3).optional().describe("System instructions for the agent."),
    personality: z2.string().trim().max(200).optional().describe("Personality style, e.g. 'Friendly'."),
    goals: z2.string().trim().max(2e3).optional().describe("What the agent should accomplish."),
    description: z2.string().trim().max(500).optional(),
    category: z2.string().trim().max(50).optional(),
    avatar_emoji: z2.string().trim().max(8).optional(),
    memory_enabled: z2.boolean().optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("agents").insert({
      user_id: ctx.getUserId(),
      name: input.name,
      role: input.role ?? "",
      system_prompt: input.system_prompt ?? "",
      personality: input.personality ?? "Friendly",
      goals: input.goals ?? "",
      tools: [],
      memory_enabled: input.memory_enabled ?? true,
      model: "google/gemini-2.5-flash",
      is_public: false,
      category: input.category ?? "general",
      description: input.description ?? "",
      avatar_emoji: input.avatar_emoji ?? "\u{1F916}"
    }).select("id, name, role, category, avatar_emoji").single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { agent: data }
    };
  }
});

// src/lib/mcp/tools/get-study-progress.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z3 } from "npm:zod@^3.25.76";
var get_study_progress_default = defineTool3({
  name: "get_study_progress",
  title: "Get study progress",
  description: "Get the signed-in student's recently completed topics and quiz attempts.",
  inputSchema: {
    limit: z3.number().int().min(1).max(50).optional().describe("Max rows per section (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const supabase = supabaseForUser(ctx);
    const n = limit ?? 10;
    const [topics, quizzes] = await Promise.all([
      supabase.from("student_topics").select("topic_name, subject, difficulty, completed_at").order("completed_at", { ascending: false }).limit(n),
      supabase.from("quiz_attempts").select("topic_name, subject, score, total_questions, percentage, attempted_at").order("attempted_at", { ascending: false }).limit(n)
    ]);
    const error = topics.error ?? quizzes.error;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const payload = { topics: topics.data ?? [], quizzes: quizzes.data ?? [] };
    return {
      content: [{ type: "text", text: JSON.stringify(payload) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/log-completed-topic.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z4 } from "npm:zod@^3.25.76";
var log_completed_topic_default = defineTool4({
  name: "log_completed_topic",
  title: "Log a completed topic",
  description: "Record a study topic the signed-in student has completed.",
  inputSchema: {
    topic_name: z4.string().trim().min(1).max(200),
    subject: z4.string().trim().min(1).max(100),
    difficulty: z4.enum(["easy", "medium", "hard"]).optional(),
    notes: z4.string().trim().max(2e3).optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("student_topics").insert({
      user_id: ctx.getUserId(),
      topic_name: input.topic_name,
      subject: input.subject,
      difficulty: input.difficulty ?? "medium",
      notes: input.notes ?? null
    }).select("id, topic_name, subject, difficulty, completed_at").single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { topic: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "fyzrouoxrrlszkrdxteo";
var mcp_default = defineMcp({
  name: "study-buddy-ai",
  title: "Study Buddy AI",
  version: "0.1.0",
  instructions: "Tools for Study Buddy AI. Use `list_agents` and `create_agent` to manage the user's custom AI agents, `get_study_progress` to read their completed topics and quiz results, and `log_completed_topic` to record new study progress. All tools act as the signed-in user.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_agents_default, create_agent_default, get_study_progress_default, log_completed_topic_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
